services:
  - type: web
    plan: free
    runtime: docker
    name: n8n-service
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_RUNNERS_DISABLED
        value: "true"
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: mammoth
      - key: NODE_FUNCTION_ALLOW_BUILTIN
        value: tls,zlib
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
databases:
  - name: n8n-db
    plan: free
